### ISSUE TITLE
Problem Statement Review

### ISSUE THREAD

**Issue by Tan630** [Tan630/Agolearn#1]
Please see [ProblemStatement.pdf](https://github.com/Tan630/Agolearn/blob/main/docs/ProblemStatementAndGoals/ProblemStatement.pdf) for the problem statement.

**Comment by smiths** [comment]
Feedback:

- spell check
- equations would help clarify what you are doing
- examples will help clarify what you are doing
- in your requirements document, type information will be very helpful
- in your requirements document, you'll want to make sure that you don't document design, but requirements - document what you want, but not how to do it.

I'm looking forward to seeing how your project comes together.  :smile:

Your project is approved.
