### ISSUE TITLE
SRS Review Issue #6 Section 4.3.1

### ISSUE THREAD

**Issue by FasilCheema** [Tan630/Agolearn#11]
There are several problems/confusion with the assumption section. I am not clear what A2 means; 'The input objective function can be higher-ordered' I think this means the input can be an n-dimensional vector however in the context of math usually high-ordered functions means a function that takes one or more functions as arguments [1]. In high school the order of function corresponds to the degree of the equation such as quadratic, cubic, quartic, etc... 

This is currently not clear and should be clarified. 

Also, A3, A5, A6, and A7 are not assumptions they are how Agolearn is defined/works, this should be cleared up.

**Comment by Tan630** [comment]
Accept in part as addressed with future actions. In commit (5dcf5541f49e416f2f94021c620a76eb28d9605a): standardize and clarify definition of higher-order functions.

Comment: I thought of them as assumptions about the problem as it is presented. I think what you say has merit and will discuss it with Dr. Smith.

**Comment by Tan630** [comment]
Resolve future action (#16) with future action.
Discussed this with Dr. Smith, who agrees that A3, A5, A6, and A7 are redundant.

**Comment by Tan630** [comment]
Resolve.Resolve future action (https://github.com/Tan630/Agolearn/issues/16) with future action.
Discussed this with Dr. Smith, who agrees that A3, A5, A6, and A7 are redundant.
