### ISSUE TITLE
Incorporate Angular Workflow

### ISSUE THREAD

**Issue by Tan630** [Tan630/Agolearn#17]
Incorporate elements of (Contributing to Angular)[https://github.com/angular/angular/blob/main/CONTRIBUTING.md] into [`CONTRIBUTING.md`](https://github.com/Tan630/Agolearn/blob/main/CONTRIBUTING.md).

Acknowledge the source of these changes, but do not add to [licenses](https://github.com/Tan630/Agolearn/tree/main/licenses). Reason: borrowed portion is insignificant.

**Comment by lyodine** [comment]
Resolve. 
In commit [b06d4ab]: change prefix rules according to Contributing to Angular; add acknowledgement

**Comment by Tan630** [comment]
Resolve.
In commit [https://github.com/Tan630/Agolearn/commit/b06d4ab9531577f8b39699b2cf19424d40ca765a]: change prefix rules according to Contributing to Angular; add acknowledgement
