### ISSUE TITLE
VnV Review

### ISSUE THREAD

**Issue by Tan630** [Tan630/Agolearn#22]
Please take a look at my [VnV plan](https://github.com/Tan630/Agolearn/blob/main/docs/VnVPlan/VnVPlan.pdf) when you feel like it.

I was allowed to experiment with a different template - if you have any comment on that, please let me know!

The pdf document is written in Word... sorry for that. Might be difficult to look at.

**Comment by tanya-jp** [comment]
@Tan630 
Hi Yiding, 

Thank you for assigning the issue to me. I've reviewed your document and noted a few minor areas for improvement. Overall, your document is excellently written!

Best regards,
Tanya
