### ISSUE TITLE
Review SRS

### ISSUE THREAD

**Issue by Tan630** [Tan630/Agolearn#3]
Link: [https://github.com/Tan630/Agolearn/blob/main/docs/SRS/SRS.pdf](https://github.com/Tan630/Agolearn/blob/main/docs/SRS/SRS.pdf)

I have compiled the SRS with all the information that is available to me. It is not perfect, and I have identified areas that may be better written, but I would not be able to make significant changes without consulting you. Another reason for this hasty commit is that the deadline is approaching - I must go to bed early, or risk being woken up by construction tomorrow morning. I do find this submission satisfactory, however.

Thank you for reviewing my writing - please be free to point out anything that you find could be better written. Critiques of any kind are greatly appreciated.

**Comment by smiths** [comment]
@Tan630 I posted about an extension until Monday on Avenue.  Maybe you didn't see that, or maybe you don't need the extra time.  It is up to you.  I'm sorry to hear about the construction.

**Comment by Tan630** [comment]
@smiths Thank you, the document is ready. Things might get better once I am forced out tomorrow to a hotel.

**Comment by smiths** [comment]
The feedback is attached.  You may wish to create issues from the feedback to organize your work and clearly show the changes between the current version and the final version.  The grade will be posted on Avenue soon.

[YidingLi_SRS.pdf](https://github.com/Tan630/Agolearn/files/14389297/YidingLi_SRS.pdf)
