### ISSUE TITLE
MG: Test Modules

### ISSUE THREAD

**Issue by omltcat** [Tan630/Agolearn#38]
First of all, what do you mean by significant defects?

It seems you are putting the test script here, which is not really necessary considering you have VnV that describes how to test the how system and each module.

**Comment by Tan630** [comment]
These modules source from requirements. They facilitate the implementation of custom operators using this framework. Modules that actually test the framework itself, on the other hand, do belong to VnV.

**Comment by Tan630** [comment]
Resolve.
