### ISSUE TITLE
Issue #1 VnV: Section 3.5.2.  Functional Requirements- FR1

### ISSUE THREAD

**Issue by FasilCheema** [Tan630/Agolearn#40]
3.5.2.  Functional Requirements- FR1: Type check input values: although it is very good you have code that indicates the test implementation I think specificity could be appreciated here. In the VnV giving specific example of a false input and a valid input can greatly improve reader understanding; also please state what type specifically the input should be. I am not clear on what the type of a s set of Genomes should be (i think real; but is this a double, long etc or is it simply a float in python?)

**Comment by Tan630** [comment]
Resolve. These requirements were developed before MG was developed and SRS was reworked. These confusions have been resolved.
