### ISSUE TITLE
SRS Review

### ISSUE THREAD

**Issue by Tan630** [Tan630/Agolearn#5]
Hi Fasil,

Please be free to review my SRS at your leisure. Any comment would be greatly appreciated.

Link: [https://github.com/Tan630/Agolearn/blob/main/docs/SRS/SRS.pdf](https://github.com/Tan630/Agolearn/blob/main/docs/SRS/SRS.pdf)

Best,
Yiding

**Comment by FasilCheema** [comment]
Thank you, was a pleasure reading your SRS looking forward to the project! :)
