### ISSUE TITLE
SRS - GS4 Is Not a Goal Statement

### ISSUE THREAD

**Issue by rnorouziani** [Tan630/Agolearn#54]
GS4, providing documentation and instructions, does not align with the definition of a Goal Statement. Goal statements should be "a functional objective the system under consideration should achieve"

**Comment by Tan630** [comment]
Resolve. This is a tricky one, but the system is required to implement behaviours that facilitate its use. For example, it provides "tests", examples, and generators that make implementation easier. I should have worded it differently.
