### ISSUE TITLE
SRS Review Issue #2 Section 4.1.1.

### ISSUE THREAD

**Issue by FasilCheema** [Tan630/Agolearn#7]
The term 'Genome' appears many times in your project as it is a critical term to your work. Unfortunately, the definition in section 4.1.1 is not satisfactory, as I am not sure what a "representation of a solution" means. Is this a vector? is it a function? There should be a definition stated here that should fully encompass what this term means so that somone reading this manual has the knowledge to understand what this project is about. Especially considereing that 5 other definitions rely on the definition of genome.

**Comment by Tan630** [comment]
Accept. In commit (ef5d6e633f566edd2ba8d362ebffac5d48dce3f8): address proposed problem. 

Comments: Thank you, these are problems I as the author would often ignore. It's a one of a kind opportunity to have someone review my writing as thoroughly as you do.
