### ISSUE TITLE
SRS Review Issue #4 Section 4.3.1

### ISSUE THREAD

**Issue by FasilCheema** [Tan630/Agolearn#9]
This is not for a specific section of your SRS but the lack of one. In your SRS you jump straight into instance models however I do not see any Theoretical Models (TM), General Definitions (GD), or Data Definitions (DD). Without these there is a lot of context behind this project that is left out. A relevant theoretical model may be that of function minimization (optimization?), gradients, matrix/vector operations, etc. These should be discussed especially if they are used in your project. The instance models themselves seem like black boxes because they simply state optimize real-valued/high-order functions, where they take an input and output an optimum. These extra definitions are needed.

**Comment by Tan630** [comment]
Accept as Pending Change.

I have talked to Dr. Smith about this. The conclusion, as I understand it, is that these models can be left out.

I had considered defining optimality (in specific terms) and evolutionary methods. I was inclined to leave them as requirements for the intended reader.

However, I do see that the assumptions use definitions such as optima and iterative optimization that are not defined as models. I believe that you are right and will talk to Dr. Smith about what could be the best way to describe these ideas.

**Comment by Tan630** [comment]
Resolve future action (#15).
Discussed the issue with Dr. Smith. Conclusion: not all models are necessary; instance models alone might be sufficient, pending review.
